name: espacogeekmobile
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.0

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  flutter_secure_storage: ^9.2.4
  crypto: ^3.0.7
  flutter_bloc: ^9.1.1
  intl: ^0.20.2
  graphql_flutter: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
