name: espacogeekmobile
description: Espa√ßo-Geek-Mobile

publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  flutter_secure_storage: ^9.2.4
  crypto: ^3.0.7
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  intl: any
  graphql_flutter: ^5.2.1
  flutter_speed_dial: ^7.0.0
  freezed_annotation: ^2.4.1
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.4.11
  freezed: ^2.5.2

flutter:
  uses-material-design: true
  generate: true
